spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/db_cloud?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
server.port=8181
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.secret=rednorteSecretKey12345678901234567890abcd
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/a08a76b3-9088-491e-a89d-b08ee3f42e46/v2.0

